deployment:
  tasks:
    - export DEPLOYPATH=/home/laciudad/public_html/
    - /opt/cpanel/nodejs/18/bin/npm install
    - /opt/cpanel/nodejs/18/bin/npm run build
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH